site_name: VCE Algorithmics Notes
site_url: https://algo.mcloughlan.com # for SEO
repo_url: https://github.com/mcloughlan/algo-notes
site_description: "A complete set of VCE Algorithmics notes. Constantly revised since 2022"
edit_uri: edit/main/docs/
theme:
  name: material
  favicon: assets/favicon.png
  logo: assets/logo.png
  features:
    - content.action.edit
    - content.code.annotate
  palette:
    - scheme: default
      primary: "blue"
      accent: "grey"
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: "blue"
      accent: "grey"
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
extra_javascript:
  - https://cdn.jsdelivr.net/npm/katex@0.16.4/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.4/dist/contrib/auto-render.min.js
  - js/math.js
extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.16.4/dist/katex.min.css
nav:
  - Home: index.md
  - Algorithms: algorithms.md
  - Graphs: graphs.md
  - Computer Science: computer-science.md
  - Extra Resources: extra-resources.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - footnotes
use_directory_urls: false
plugins:
  - search
  - git-revision-date-localized
  - macros # For contribution icons
  - social # For embeds
